### ISSUE TITLE
License clarification... 

### ISSUE THREAD

**Issue by abhas** [AnaviTechnology/anavi-light#1]
Hi,

I recently discovered your project via Crowd Supply and was glad to learn about its utility and novelty.

However, I see a contradiction in your licensing and wanted to seek a clarification for the same.

In your README, you state that the project is licensed under the " Creative Commons Attribution-NonCommercial 3.0 Unported (CC BY-NC 3.0)" license. However, elsewhere on the same page you use say that anavi-light is a "open source hardware Raspberry Pi pHAT". This is where I see a contradiction.

The Open Source Hardware (OSHW) definition (available at: https://www.oshwa.org/definition/) clearly states that:

> 4. Derived Works
The license shall allow modifications and derived works, and shall allow them to be distributed under the same terms as the license of the original work. The license shall allow for the manufacture, sale, distribution, and use of products created from the design files, the design files themselves, and derivatives thereof.

> 8. No Discrimination Against Fields of Endeavor
The license must not restrict anyone from making use of the work (including manufactured hardware) in a specific field of endeavor. For example, it must not restrict the hardware from being used in a business, or from being used in nuclear research.

So the CC BY-NC license would conflict with these terms.

What you are doing is really very admirable. I wanted to check if you are aware of such terms regarding OSHW.

Also -- please do submit your project for listing on the OSHWA Certification Directory (http://certificate.oshwa.org/certification-directory/) so that more people might discover your project and be able to use it.

All the best!

**Comment by leon-anavi** [comment]
Hi @abhas,

Thank you for the feedback. I wasn't not aware about these details. ANAVI Light pHAT is a hobby project and priority #1 is the community. I am ready change the license in order to make it more community friendly.  Would you recommend me switching to Creative Commons Share-alike 4.0 International or Creative Commons Attribution-Share Alike 3.0 United States License?

Thanks,
Leon

**Comment by abhas** [comment]
I think Creative Commons Share-alike 4.0 International should be good. It protects your interests and also provides essential freedom with others.

You can also add that anavi-light is "_Open Source Hardware as defined by the Open Source Hardware (OSHW) Definition 1.0_". This definition is available at: https://www.oshwa.org/definition/

Do check the definition to see that it meets your needs. My reason of raising this issue was that a lot of times people use the term "open source hardware" without really examining the OSHW definition in detail.

Meanwhile, looking forward to your campaign on crowd supply!

**Comment by leon-anavi** [comment]
Hi @abhas,

Following your recommendations I have switched the license to CC BY-SA 4.0 in git commit 12eb55df7d9b371fd6cdabf9f96e7d573fa7e152. 

Since a few hours the campaign at Crowd Supply is [live](https://www.crowdsupply.com/anavi-technology/light-phat) :) 

Thanks,
Leon
