### ISSUE TITLE
Any code samples for python?

### ISSUE THREAD

**Issue by emanuelstanciu** [AnaviTechnology/anavi-light#2]
Hi @leon-anavi,

Thanks for sending this through. The hardware looks amazing, great work.
Any chance you can share sample code to control it?

Thanks,
Emanuel

**Comment by leon-anavi** [comment]
Hi @emanuelstanciu, 

Please have a look at [the provided examples](https://github.com/AnaviTechnology/anavi-examples/tree/master/anavi-light-phat/light-demo) and the [user's manual](https://github.com/AnaviTechnology/anavi-docs/tree/master/anavi-light-phat). There is also an option to integrate [ANAVI Light pHAT with Home Assistant](https://github.com/AnaviTechnology/anavid/blob/master/README.md).

Thanks,
Leon

**Comment by emanuelstanciu** [comment]
Actually, I think [this](https://github.com/AnaviTechnology/anavid) might prove more useful for others as well.. I can have a standalone mqtt broker and link it with a main hub for IoT purposes
thanks, will report back with results
